name: xgboost-cell-classification-gpu
channels:
- rapidsai
- nvidia
- conda-forge
dependencies:
- py-xgboost=1.7.4
- scikit-learn=1.1.1
- scikit-optimize=0.9.0
- imbalanced-learn=0.9.1
- pandas=1.4.4
- numpy<1.20
- toml